-- テーブル作成

CREATE TABLE T_ORDER
( ORDER_NO NUMERIC(3) CONSTRAINT PK_ORDER_NO PRIMARY KEY,
  ITEM_NO  NUMERIC(4),
  QUANTITY NUMERIC(3),
  AMOUNT   NUMERIC(7),
  DELIVERY_DATE DATE
);


CREATE TABLE T_ITEM
( ITEM_NO NUMERIC(4) CONSTRAINT PK_ITEM_NO PRIMARY KEY,
  ITEM_NAME  VARCHAR(20),
  PRICE   NUMERIC(4)
);
